### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: livekit/LivekitModels$Room

### ISSUE THREAD

**Issue by zoujiaqing** [livekit/server-sdk-kotlin#95]
I use server-sdk-koltin in my springboot 3.4.x project.

maven add dependency:

```xml
<dependencies>
    <dependency>
        <groupId>io.livekit</groupId>
        <artifactId>livekit-server</artifactId>
        <version>0.8.3</version>
    </dependency>
</dependencies>
```

Create a service class RoomService have craeteRoom fucntion.

Application error on start:

```log
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'roomService': Lookup method resolution failed
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.checkLookupMethods(AutowiredAnnotationBeanPostProcessor.java:498)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:368)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1314)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1209)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:205)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.resolveBeanByName(AbstractAutowireCapableBeanFactory.java:461)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:605)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:576)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:738)
	at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:270)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:145)
	at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessProperties(CommonAnnotationBeanPostProcessor.java:368)
	... 17 common frames omitted
Caused by: java.lang.IllegalStateException: Failed to introspect Class [com.gitlab.neton.module.iot.service.device.RoomService] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@76ed5528]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:483)
	at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:320)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.checkLookupMethods(AutowiredAnnotationBeanPostProcessor.java:476)
	... 33 common frames omitted
Caused by: java.lang.NoClassDefFoundError: livekit/LivekitModels$Room
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2676)
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:465)
	... 35 common frames omitted
Caused by: java.lang.ClassNotFoundException: livekit.LivekitModels$Room
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 39 common frames omitted
```

**Comment by ooraini** [comment]
Similar issue after upgrading to Spring Boot 3.4:
```

Caused by: java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3 |  
-- | --
  |   | 2025-04-13 14:35:00.032 | at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) |  
  |   | 2025-04-13 14:35:00.032 | at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1555) |  
  |   | 2025-04-13 14:35:00.032 | at org.springframework.boot.loader.launch.LaunchedClassLoader.loadClass(LaunchedClassLoader.java:91) |  
  |   | 2025-04-13 14:35:00.032 | at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) |  
  |   | 2025-04-13 14:35:00.032 | at java.base/java.lang.ClassLoader.defineClass(Unknown Source) |  
  |   | 2025-04-13 14:35:00.032 | at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:64) |  
  |   | 2025-04-13 14:35:00.032 | at java.base/java.lang.Class.getDeclaredMethods0(Native Method) |  
  |   | 2025-04-13 14:35:00.032 | at org.springframework.boot.SpringApplication.run(SpringApplication.java:1350)


```

**Comment by ooraini** [comment]
> Similar issue after upgrading to Spring Boot 3.4:
> 
> ```
> 
> Caused by: java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3 |  
> -- | --
>   |   | 2025-04-13 14:35:00.032 | at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) |  
>   |   | 2025-04-13 14:35:00.032 | at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1555) |  
>   |   | 2025-04-13 14:35:00.032 | at org.springframework.boot.loader.launch.LaunchedClassLoader.loadClass(LaunchedClassLoader.java:91) |  
>   |   | 2025-04-13 14:35:00.032 | at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) |  
>   |   | 2025-04-13 14:35:00.032 | at java.base/java.lang.ClassLoader.defineClass(Unknown Source) |  
>   |   | 2025-04-13 14:35:00.032 | at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:64) |  
>   |   | 2025-04-13 14:35:00.032 | at java.base/java.lang.Class.getDeclaredMethods0(Native Method) |  
>   |   | 2025-04-13 14:35:00.032 | at org.springframework.boot.SpringApplication.run(SpringApplication.java:1350)
> ```


This was due to [MySQL Connector/J](https://mvnrepository.com/artifact/com.mysql/mysql-connector-j) using version 4 of protobuf-java which is incompatible with the livekit-sdk. I changed the version of connector/J and it works:
```
// build.gradle.kts
extra["mysql.version"] = "8.4.0"
```

**Comment by ericsanjaya** [comment]
> > Similar issue after upgrading to Spring Boot 3.4:
> > ```
> > 
> > Caused by: java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3 |  
> > -- | --
> >   |   | 2025-04-13 14:35:00.032 | at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) |  
> >   |   | 2025-04-13 14:35:00.032 | at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1555) |  
> >   |   | 2025-04-13 14:35:00.032 | at org.springframework.boot.loader.launch.LaunchedClassLoader.loadClass(LaunchedClassLoader.java:91) |  
> >   |   | 2025-04-13 14:35:00.032 | at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) |  
> >   |   | 2025-04-13 14:35:00.032 | at java.base/java.lang.ClassLoader.defineClass(Unknown Source) |  
> >   |   | 2025-04-13 14:35:00.032 | at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:64) |  
> >   |   | 2025-04-13 14:35:00.032 | at java.base/java.lang.Class.getDeclaredMethods0(Native Method) |  
> >   |   | 2025-04-13 14:35:00.032 | at org.springframework.boot.SpringApplication.run(SpringApplication.java:1350)
> > ```
> 
> This was due to [MySQL Connector/J](https://mvnrepository.com/artifact/com.mysql/mysql-connector-j) using version 4 of protobuf-java which is incompatible with the livekit-sdk. I changed the version of connector/J and it works:
> 
> ```
> // build.gradle.kts
> extra["mysql.version"] = "8.4.0"
> ```

Thanks for the detailed report!

I also ran into the same issue when upgrading to Spring Boot 3.4, and confirmed it's due to the mysql-connector-j using Protobuf v4, which currently conflicts with livekit-sdk.

I plan to submit a pull request to update the Protobuf dependency in livekit-sdk to version 4 to help resolve this.

Appreciate you sharing the solution — it helped me track down the root cause faster
